### ISSUE TITLE
authenticatorapi.com site broken?

### ISSUE THREAD

**Issue by dani3l3** [infiniteloopltd/AuthenticatorAPI.com#1]
It gives a connection reset when connecting over https. Works over http... but seriously, should I do 2FA over http?

Is this still maintained? Also infiniteloop.ie seems down, are you guys still in business? 

Thanks

**Comment by lelala** [comment]
same problem, can't connect to https, but http still available

**Comment by infiniteloopltd** [comment]
Hi, the https certificate has now been applied to the website. It was not applied during a server migration, but is available now.
